// src/pages/HomePage.vue
<!--
  HomePage.vue – Main landing page content.
  Renders the hero section: greeting row, typewriter headline, bio paragraph.
  The outer shell (background, header, chat widget) is provided by AppLayout.vue.
-->

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import RotatingDescriptor from '@/components/RotatingDescriptor.vue'

const hasScrolled = ref(false)
function onScroll() { hasScrolled.value = window.scrollY > 40 }
onMounted(() => window.addEventListener('scroll', onScroll, { passive: true }))
onUnmounted(() => window.removeEventListener('scroll', onScroll))

/** Placeholder project data until real case studies and routes exist. */
const PLACEHOLDER_PROJECTS = [
  {
    title: "Building Ecosia's Onboarding Experience",
    tagline: 'A smooth first-time experience that boosted conversion by 25%.',
    slug: 'ecosia-onboarding',
  },
  {
    title: 'Scaling Design Operations at Ecosia',
    tagline: "Establishing a shared ownership model for Ecosia's Design System – Flora.",
    slug: 'ecosia-ops',
  },
  {
    title: 'Install Funnel for the Ecosia Browser',
    tagline: "Launched Ecosia's browser in just two months, reaching 100k DAU.",
    slug: 'ecosia-browser',
  },
]
</script>

<template>
  <!-- Hero: greeting row, typewriter headline, and bio paragraph -->
  <section
    class="relative h-screen p-[40px]"
    aria-labelledby="hero-heading"
  >
    <!-- Whiteboard panel: fills the viewport minus 80px on all sides -->
    <div
      class="w-full h-full rounded-3xl flex items-start overflow-y-auto px-10 lg:px-20"
      style="
        background-color: #f7f6f2;
        background-image: radial-gradient(circle, rgba(0,0,0,0.13) 1.2px, transparent 1.2px);
        background-size: 22px 22px;
        border: 1px solid rgba(0,0,0,0.06);
      "
    >
      <div class="w-full flex flex-col gap-8 pt-16 mt-20">
      <div class="flex flex-col-reverse items-center justify-center gap-10 lg:flex-row lg:items-center lg:gap-[102px]">
      <!-- Left: headline -->
      <div class="flex-1 w-full lg:w-auto lg:max-w-[720px] min-w-0">
        <h1
          id="hero-heading"
          class="font-heading mt-2 text-5xl font-black leading-tight tracking-tight text-[var(--color-headline)] lg:text-7xl"
        >
          <span class="block">I'm a</span>
          <span class="block"><RotatingDescriptor /></span>
          <span class="block">who creates with clarity and purpose.</span>
        </h1>
      </div>

      <!-- OPTION A — STICKY NOTE (active) -->
      <div class="relative shrink-0 w-64 lg:w-80" style="aspect-ratio: 1 / 1; transform: rotate(2deg)">
        <div class="absolute z-10" style="width: 5.5rem; height: 2.1rem; top: -1rem; left: 50%; transform: translateX(-50%) rotate(-3deg); background: rgba(210, 228, 255, 0.68); box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.4), 0 1px 2px rgba(0, 0, 0, 0.10);"></div>
        <div class="absolute inset-0 flex flex-col" style="background: #f2c96c; box-shadow: 1px 2px 3px rgba(0, 0, 0, 0.08), 4px 10px 20px rgba(0, 0, 0, 0.18), 8px 24px 48px rgba(0, 0, 0, 0.12);">
          <div class="relative flex-1 overflow-hidden mx-9 mt-9 mb-9">
            <img src="/timea.png" alt="Timea Konya" class="w-full h-full object-cover object-top" />
            <div class="absolute inset-0 border-4 border-white pointer-events-none"></div>
          </div>
        </div>
        <!-- Pointer: X and Y on separate elements with coprime durations (7s/5s) -->
        <!-- so the combined path is a curved Lissajous that doesn't repeat for 35s -->
        <div class="absolute pointer-events-none pointer-float-x" style="width: 7rem; bottom: calc(-2rem + 5px); right: calc(1rem - 30px);">
          <img src="/pointer.svg" alt="" aria-hidden="true" class="pointer-float-y w-full" />
        </div>
      </div>
      </div>

      <!-- Description: sits below the headline + image row -->
      <p class="mt-20 text-lg text-[var(--color-muted)] max-w-2xl mx-auto text-center">
        People describe me as
        <strong class="font-semibold text-[var(--color-brand)]"
          >thoughtful, analytical, and structured</strong
        > – someone who cuts through ambiguity and connects dots others miss. I care about making design inclusive, accessible, and used for something genuinely good.
      </p>


      </div>

      <!-- =====================================================================
        OPTION B — POLAROID (parked, may revisit)
        Square polaroid frame, white border thicker at bottom, tape on top.
        To restore: uncomment the block below and remove the sticky note block.
      ======================================================================
      <div class="relative shrink-0 w-64 lg:w-80" style="aspect-ratio: 1 / 1; transform: rotate(-2deg)">
        <div class="absolute z-10" style="width: 5.5rem; height: 2.1rem; top: -1rem; left: 50%; transform: translateX(-50%) rotate(3deg); background: rgba(210, 228, 255, 0.68); box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.4), 0 1px 2px rgba(0, 0, 0, 0.10);"></div>
        <div class="absolute inset-0 flex flex-col" style="background: #ffffff; padding: 0.6rem 0.6rem 2rem 0.6rem; box-shadow: 1px 2px 3px rgba(0, 0, 0, 0.08), 4px 10px 20px rgba(0, 0, 0, 0.18), 8px 24px 48px rgba(0, 0, 0, 0.12);">
          <div class="flex-1 overflow-hidden">
            <img src="/timea.png" alt="Timea Konya" class="w-full h-full object-cover object-top" />
          </div>
        </div>
      </div>
      ===================================================================== -->
    </div>

  </section>
</template>

<style scoped>
/*
  Natural float via Lissajous with coprime periods: X=7s, Y=5s.
  The path doesn't repeat for 35s, and ease-in-out on each axis keeps transitions curved.
*/
.pointer-float-x {
  animation: pointer-float-x 7s ease-in-out infinite;
}
.pointer-float-y {
  animation: pointer-float-y 5s ease-in-out infinite;
}

@keyframes pointer-float-x {
  0%   { transform: translateX(0px); }
  50%  { transform: translateX(16px); }
  100% { transform: translateX(0px); }
}

@keyframes pointer-float-y {
  0%   { transform: translateY(0px); }
  50%  { transform: translateY(12px); }
  100% { transform: translateY(0px); }
}

.scroll-dot {
  transform-box: fill-box;
  transform-origin: center top;
  animation: scroll-wheel 2s ease-in-out infinite;
}

@keyframes scroll-wheel {
  0%   { transform: translateY(0); }
  50%  { transform: translateY(14px); }
  100% { transform: translateY(0); }
}
</style>

// src/components/HomePage.jsx
/**
 * HomePage
 * ---------
 * Main landing page: hero (intro + typewriter headline), bio paragraph, and featured project cards.
 * Uses theme CSS variables for colors so every theme looks consistent.
 * No router yet – project and About pages are placeholders for later.
 */

import { Header } from './Header';
import { Logo } from './Logo';
import { RotatingDescriptor } from './RotatingDescriptor';

/** Placeholder project data until real case studies and routes exist. slug is used as list key and future route. */
const PLACEHOLDER_PROJECTS = [
  { title: "Building Ecosia's Onboarding Experience", tagline: "A smooth first-time experience that boosted conversion by 25%.", slug: 'ecosia-onboarding' },
  { title: "Scaling Design Operations at Ecosia", tagline: "Establishing a shared ownership model for Ecosia's Design System – Flora.", slug: 'ecosia-ops' },
  { title: "Install Funnel for the Ecosia Browser", tagline: "Launched Ecosia's browser in just two months, reaching 100k DAU.", slug: 'ecosia-browser' },
];

export function HomePage() {
  return (
    <div className="min-h-screen bg-[var(--color-surface)]">
      <Header />

      <main>
        {/* Hero: greeting, logo, typewriter headline, and short bio. aria-labelledby links section to h1 for screen readers. */}
        <section className="mx-auto max-w-6xl px-4 py-16 md:py-24" aria-labelledby="hero-heading">
          <div className="flex flex-wrap items-center gap-2">
            <p className="text-lg font-semibold text-[var(--color-muted)] md:text-xl">Hi, I&apos;m</p>
            <Logo className="h-7 w-auto md:h-8" />
            <span className="sr-only">Timea</span>
          </div>
          <h1 id="hero-heading" className="mt-2 max-w-3xl text-4xl font-bold leading-tight tracking-tight text-[var(--color-headline)] md:text-5xl">
            I&apos;m a <RotatingDescriptor /> who creates with clarity and purpose.
          </h1>
          <p className="mt-6 max-w-2xl text-lg text-[var(--color-muted)]">
            People describe me as <strong className="font-semibold text-[var(--color-brand)]">thoughtful, analytical, and structured</strong>. I enjoy connecting dots others miss and bringing clarity to ambiguity through deep thinking and systematic problem solving. I care about making design inclusive and accessible, and about using it for something genuinely good.
          </p>
        </section>

        {/* Featured projects: grid of placeholder cards. id="projects" is the anchor for future in-page links. */}
        <section id="projects" className="mx-auto max-w-6xl px-4 py-12" aria-labelledby="projects-heading">
          <h2 id="projects-heading" className="text-2xl font-bold text-[var(--color-brand)]">
            Recent Projects
          </h2>
          <p className="mt-2 text-[var(--color-muted)]">
            Here are some examples of how I work with cross-functional teams, and how I blend research, evaluation and execution.
          </p>
          <ul className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {PLACEHOLDER_PROJECTS.map((p) => (
              <li key={p.slug}>
                <article className="overflow-hidden rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-elevated)] transition-[var(--a11y-motion)] hover:shadow-md">
                  {/* Placeholder image block – replace with real image or link when project pages exist */}
                  <div
                    className="h-40 w-full bg-[var(--color-border)]"
                    aria-hidden="true"
                  />
                  <div className="p-4">
                    <h3 className="font-semibold text-[var(--color-brand)]">{p.title}</h3>
                    <p className="mt-1 text-sm text-[var(--color-muted)]">{p.tagline}</p>
                    <span className="mt-3 inline-block text-sm font-medium text-[var(--color-brand)]">
                      Read case study →
                    </span>
                  </div>
                </article>
              </li>
            ))}
          </ul>
        </section>
      </main>

      {/* Footer: copyright and placeholder links. Update hrefs when real URLs are ready. */}
      <footer className="border-t border-[var(--color-border)] bg-[var(--color-surface-elevated)] px-4 py-6">
        <div className="mx-auto flex max-w-6xl justify-between text-sm text-[var(--color-muted)]">
          <span>© Timea Konya</span>
          <div className="flex gap-4">
            <a href="#" className="hover:text-[var(--color-brand)]">LinkedIn</a>
            <a href="#" className="hover:text-[var(--color-brand)]">Download CV</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
