// src/components/ThemeSwitcher.vue
<!--
  ThemeSwitcher.vue – Theme selection dropdown.
  Opens a listbox of available themes on button click. Selecting one calls store.setTheme(),
  which swaps the theme-* class on <html> and persists the choice. Closes on outside click
  (document listener added on mount, removed on unmount).
-->

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { useThemeStore } from '@/stores/theme'

const store = useThemeStore()

/** Whether the dropdown listbox is open. */
const open = ref(false)

/** Ref to the wrapper div so we can detect clicks outside the component. */
const containerRef = ref<HTMLElement | null>(null)

/** Display name for each theme id. */
const LABELS: Record<string, string> = {
  default: 'Default',
  bauhaus: 'Bauhaus',
  terminal: 'Terminal',
  'neo-brutalism': 'Neo-brutalism',
  sketch: 'Sketch',
  retro: 'Retro',
  material: 'Material Design',
}

/** Short adjective-based description shown under each theme name. */
const DESCRIPTIONS: Record<string, string> = {
  default: 'Warm, violet, editorial serif',
  bauhaus: 'Bold, geometric, primary palette',
  terminal: 'Dark, monospace, hacker green',
  'neo-brutalism': 'Raw, loud, hard shadows',
  sketch: 'Soft, paper, dotted grid',
  retro: 'Silver, beveled, 90s nostalgia',
  material: 'Clean, elevated, corporate blue',
}

/** Close if the user clicks anywhere outside the component. */
function handleOutsideClick(e: MouseEvent) {
  if (containerRef.value && !containerRef.value.contains(e.target as Node)) {
    open.value = false
  }
}

onMounted(() => document.addEventListener('click', handleOutsideClick))
onUnmounted(() => document.removeEventListener('click', handleOutsideClick))

/** Select a theme and close the dropdown. */
function selectTheme(id: string) {
  store.setTheme(id)
  open.value = false
}
</script>

<template>
  <div class="relative" ref="containerRef">
    <button
      type="button"
      @click="open = !open"
      class="flex items-center gap-1 rounded border border-[var(--color-border)] bg-[var(--color-surface-elevated)] px-3 py-2 text-sm font-medium text-[var(--color-muted)] hover:text-[var(--color-brand)] focus-visible:outline-offset-2"
      aria-haspopup="listbox"
      :aria-expanded="open"
      aria-label="Choose theme"
    >
      Themes
    </button>

    <ul
      v-if="open"
      role="listbox"
      class="absolute right-0 top-full z-10 mt-1 min-w-[16rem] rounded border border-[var(--color-border)] bg-[var(--color-surface-elevated)] py-1 shadow-lg"
      aria-label="Theme options"
    >
      <li
        v-for="id in store.themes"
        :key="id"
        role="option"
        :aria-selected="store.theme === id"
      >
        <button
          type="button"
          class="w-full px-4 py-2 text-left text-sm hover:bg-[var(--color-surface)] hover:text-[var(--color-brand)] focus:bg-[var(--color-surface)] focus:text-[var(--color-brand)] focus:outline-none"
          @click="selectTheme(id)"
        >
          <span class="font-medium">{{ LABELS[id] ?? id }}</span>
          <span v-if="DESCRIPTIONS[id]" class="block text-xs opacity-60">{{ DESCRIPTIONS[id] }}</span>
        </button>
      </li>
    </ul>
  </div>
</template>

// src/components/ThemeSwitcher.jsx
/**
 * ThemeSwitcher
 * -------------
 * Dropdown button that shows the current theme name and, when opened, a list of all themes.
 * Selecting an option calls setTheme(id) from ThemeContext; the context then updates <html> class
 * and localStorage. Clicking outside the dropdown closes it (useRef + effect).
 */

import { useState, useRef, useEffect } from 'react';

/** Display names for each theme id (used in the button label and list options). */
const LABELS = {
  bauhaus: 'Bauhaus',
  terminal: 'Terminal',
  'neo-brutalism': 'Neo-brutalism',
  sketch: 'Sketch',
  retro: 'Retro',
  material: 'Material Design',
};

export function ThemeSwitcher({ theme, setTheme, themes }) {
  const [open, setOpen] = useState(false);
  const ref = useRef(null);

  /** Close dropdown when user clicks outside the component. */
  useEffect(() => {
    function close(e) {
      if (ref.current && !ref.current.contains(e.target)) setOpen(false);
    }
    document.addEventListener('click', close);
    return () => document.removeEventListener('click', close);
  }, []);

  return (
    <div className="relative" ref={ref}>
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="flex items-center gap-1 rounded border border-[var(--color-border)] bg-[var(--color-surface-elevated)] px-3 py-2 text-sm font-medium text-[var(--color-muted)] hover:text-[var(--color-brand)] focus-visible:outline-offset-2"
        aria-haspopup="listbox"
        aria-expanded={open}
        aria-label="Choose theme"
      >
        <span aria-hidden>◇</span> {LABELS[theme] ?? theme}
      </button>
      {open && (
        <ul
          role="listbox"
          className="absolute right-0 top-full z-10 mt-1 min-w-[10rem] rounded border border-[var(--color-border)] bg-[var(--color-surface-elevated)] py-1 shadow-lg"
          aria-label="Theme options"
        >
          {themes.map((id) => (
            <li key={id} role="option" aria-selected={theme === id}>
              <button
                type="button"
                className="w-full px-4 py-2 text-left text-sm hover:bg-[var(--color-surface)] hover:text-[var(--color-brand)] focus:bg-[var(--color-surface)] focus:text-[var(--color-brand)] focus:outline-none"
                onClick={() => {
                  setTheme(id);
                  setOpen(false);
                }}
              >
                {LABELS[id] ?? id}
              </button>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
