// src/App.jsx
/**
 * App
 * ---
 * Root layout: wraps the app in ThemeProvider and A11yProvider so theme and accessibility
 * preferences are available everywhere and persist (localStorage). Imports theme CSS so
 * --color-* and --font-* variables are applied when the theme class is set on <html>.
 * Currently renders only HomePage; add a router here when adding About and project pages.
 */

import { ThemeProvider } from './context/ThemeContext';
import { A11yProvider } from './context/A11yContext';
import { HomePage } from './components/HomePage';
import './themes/index.css';

function App() {
  return (
    <ThemeProvider>
      <A11yProvider>
        <HomePage />
      </A11yProvider>
    </ThemeProvider>
  );
}

export default App;

// src/App.vue
<!--
  App.vue – Root component.
  Imports the theme CSS so --color-* and --font-* CSS variables are available globally.
  Accessing the stores here ensures their watchers run before the first render,
  so theme classes and a11y CSS vars are applied to <html> before anything is painted.
-->

<script setup lang="ts">
import { useThemeStore } from '@/stores/theme'
import { useA11yStore } from '@/stores/a11y'
import HomePage from '@/components/HomePage.vue'
import '@/themes/index.css'

// Initialise stores on app boot — their immediate watchers apply HTML classes and CSS vars
useThemeStore()
useA11yStore()
</script>

<template>
  <HomePage />
</template>
